CREATE TABLE forms(
       id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       login VARCHAR(128)                            NOT NULL,
       salt  VARCHAR(32)                             NOT NULL,
       email varchar(255)                            NOT NULL
);