CREATE TABLE events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(250),
    start_date   TIMESTAMP WITHOUT TIME ZONE,
    end_date     TIMESTAMP WITHOUT TIME ZONE,
    description  VARCHAR(2000),
    organizer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR(128)                            NOT NULL,
    hash  VARCHAR(64)                             NOT NULL,
    salt  VARCHAR(32)                             NOT NULL,
    type  VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES users (id);