CREATE TABLE events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(250),
    start_date   TIMESTAMP WITHOUT TIME ZONE,
    end_date     TIMESTAMP WITHOUT TIME ZONE,
    description  VARCHAR(2000),
    organizer_id BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR(255)                            NOT NULL,
    hash  VARCHAR(255)                            NOT NULL,
    salt  VARCHAR(255)                            NOT NULL,
    type  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
