CREATE TABLE ticket_types (
     id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     event_id           BIGINT NOT NULL,
     name               VARCHAR(100) NOT NULL,
     price              NUMERIC(10, 2) NOT NULL,
     quantity_available INT,
     FOREIGN KEY (event_id) REFERENCES events(id),
     CONSTRAINT pk_ticket_types PRIMARY KEY (id)
);

CREATE TABLE tickets (
     id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     event_id               BIGINT NOT NULL,
     ticket_type_id         BIGINT NOT NULL,
     holder_id              BIGINT NOT NULL,
     ticket_purchase_date   DATE NOT NULL,
     FOREIGN KEY (event_id) REFERENCES events(id),
     FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(id),
     FOREIGN KEY (holder_id) REFERENCES users(id),
     CONSTRAINT pk_tickets PRIMARY KEY (id)
);
