CREATE TABLE event_images (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id                BIGINT NOT NULL,
    image                   bytea NOT NULL,
    CONSTRAINT pk_event_images PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES events(id)
)