CREATE TABLE event_sections (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id                BIGINT NOT NULL,
    name                    VARCHAR(64) NOT NULL,
    capacity                INT NOT NULL,
    CONSTRAINT pk_event_sections PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES events(id)
);

DELETE FROM tickets;

ALTER TABLE tickets ADD section_id BIGINT NOT NULL CONSTRAINT tickets_section_id REFERENCES event_sections(id);

ALTER TABLE event_images ADD section_map BOOLEAN NOT NULL DEFAULT FALSE;

INSERT INTO event_sections (event_id, name, capacity) VALUES (1, 'strefa kibica', 2500),
(1, 'trybuna A', 5000),
(2, 'Miejsca siedzące - Stefa B', 1000),
(2, 'Miejsca stojące pod sceną', 250),
(2, 'Loża VIP', 100);
