SET client_encoding = 'UTF8';

CREATE ROLE apsi WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD 'apsi';

GRANT CONNECT ON DATABASE apsidb TO apsi;
GRANT USAGE ON SCHEMA public TO apsi;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO apsi;
GRANT CREATE ON SCHEMA public TO apsi;
ALTER DEFAULT PRIVILEGES FOR ROLE apsi IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO apsi;
